name: Deploy BackEnd changes to AWS Lambda

on:
  push:
    branches:
      - dev
    paths:
        - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    # - name: Identify changed files
    #   id: getfile
    #   run: |
    #     FILES=$(git diff --name-only origin/main)
    #     echo "Modified files: $FILES"
    #     echo "::set-output name=files::$FILES"

    - name: Deploy modified functions
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Deploying get_alarm_metrics..."
        zip -r get_alarm_metrics.zip backend/get_alarm_metrics.py
        aws lambda update-function-code --function-name get_alarm_metrics --zip-file fileb://get_alarm_metrics.zip
        
        echo "Deploying get_metrics..."
        zip -r get_metrics.zip backend/get_metrics.py
        aws lambda update-function-code --function-name get_metrics --zip-file fileb://get_metrics.zip
      
        echo "Deploying get_rss..."
        zip -r get_rss.zip backend/get_rss.py
        aws lambda update-function-code --function-name get_rss --zip-file fileb://get_rss.zip
        
        
 
  
  
  
  
  
  
